import { Config } from "ziggy-js";

export interface User {
    id: number;
    name: string;
    email: string;
    email_verified_at: string;
}

export type PageProps<
    T extends Record<string, unknown> = Record<string, unknown>
> = T & {
    auth: {
        user: User;
    };
    ziggy: Config & { location: string };
};

// Generated by https://quicktype.io

export interface Painting {
    id: number;
    title: string;
    description: string;
    short_description: string;
    post: string;
    medium: string;
    size: string;
    price: number;
    active: number;
    created_at: string;
    updated_at: string;
    painting: string;
    painting_id: string;
}
